package xyz.dgz48.tasks.webapi.audit.domain;

/** audit_logs.action に記録するイベント種別。 */
public enum AuditEventType {
  TASK_CREATED,
  TASK_UPDATED,
  TASK_DELETED,
  VISIBILITY_CHANGED,
  STAKEHOLDER_PURGED,
  STAKEHOLDER_ADDED,
  STAKEHOLDER_REMOVED,

  // テナント運営系 (ADR-0020 §3.3)
  TENANT_CREATED,
  TENANT_SUSPENDED,
  TENANT_REACTIVATED,
  TENANT_UPDATED,
  TENANT_VIEWED,
  TENANT_LIST_VIEWED,
  PLATFORM_METRICS_VIEWED,

  // ユーザーライフサイクル / 認証 (ADR-0006 §3.4 / §3.3, #734)
  ANONYMIZE,
  LOGIN_FAILED,

  // 認可違反 (基本設計書 §4.2.6 / §6.2.3, #734)。記録配線は #736 で実施(語彙のみ先行追加)。
  // TENANT_CROSSED は旧 CROSS_TENANT_VIOLATION_ATTEMPT を設計標準語彙へ改称したもの(本 issue で記録配線済み)。
  VIEW_DENIED,
  EDIT_DENIED,
  DELETE_DENIED,
  STATUS_CHANGE_DENIED,
  VISIBILITY_CHANGE_DENIED,
  STAKEHOLDER_EDIT_DENIED,
  TENANT_CROSSED,
  ROLE_BASED_DENIED
}
